### ISSUE TITLE
Miscellaneous warnings in generated C code

### ISSUE THREAD

**Issue by franziskuskiefer** [FStarLang/karamel#363]
Tracking issue to fix miscellaneous warnings in generated C code.

See https://github.com/hacl-star/hacl-star/issues/843 for a list of warnings.

**Comment by prosecco** [comment]
The following patch proposed by @protz works well for all the unused-but-set warnings in HACL*.
```
diff --git a/dist/karamel/include/krml/internal/target.h b/dist/karamel/include/krml/internal/target.h
index 9eb260c630..a378ed4f4b 100644
--- a/dist/karamel/include/krml/internal/target.h
+++ b/dist/karamel/include/krml/internal/target.h
@@ -169,6 +169,7 @@ inline static int32_t krml_time(void) {
 #define KRML_LOOP1(i, n, x) { \
   x \
   i += n; \
+  (void) i; \
 }
 
 #define KRML_LOOP2(i, n, x) \
```

**Comment by msprotz** [comment]
With the latest round of fixes regarding possibly unused variables, the code now compiles with the following flags:

https://github.com/FStarLang/karamel/blob/da83fc312e2f3833f5746dfb702a456048a7a3da/misc/Makefile.basic#L15-L17

namely, -Wall -Wextra -Werror with the addition of -Wno-infinite-recursion since F* doesn't prevent this by default.

Now there are MANY more warnings beyond those enabled by -Wall and -Wextra -- see https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html for instance. Those should be discussed on a case-by-base basis, because there's no consensus that these "extra extra" warnings are helpful. I'm thinking for instance about -Wpedantic, which gives this:

```
./curve25519-inline.h:218:5: error: string literal of length 4266 exceeds maximum length 4095 that ISO C99 compilers are required to support [-Werror,-Woverlength-strings]
    "  movq 0(%0), %%rdx;"
    ^~~~~~~~~~~~~~~~~~~~~~
```

in the build of HACL, or -Wimplicit-int-conversions which gives a TON of errors, most of which are innocuous (in particular, since #387, assignments of uint8 or uint16 computations always triggers a warning).

Conversely, some warnings are enabled by -Wextra -Wall but it's up to the user to do something about it, since krml won't work around them (thinking about -Wset-but-unused for instancen which krml could conceivably work to defeat, but again, better to discuss in a specific issue).

So I'm closing this, but happy to discuss any new issue about a specific C compiler warning that krml should guard against (i.e., make sure is never triggered).
